name: Devops SonarQube Analysis by Akash
 
on:
  push:
    branches:
      - main
 
jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Run SonarScanner
        run: |
          docker run --rm -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=akash-java-sonar \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://13.232.4.242:9091 \
            -Dsonar.login=sqp_a8dfbba39540625458a16134c0d016eb3c6a80f5
