name: DevOps Java CI/CD Pipeline and SonarQube by Akash

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run SonarScanner
        run: |
          docker run --rm -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=akash-java-sonar \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://13.232.4.242:9091 \
            -Dsonar.login=sqp_a8dfbba39540625458a16134c0d016eb3c6a80f5

  build-and-push:
    runs-on: ubuntu-latest
    needs: sonar  # Runs only after SonarQube completes successfully
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}

      - name: Build Docker Image
        run: |
          docker build -t akashigt/akash-java-sonar:v1 .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push akashigt/akash-java-sonar:v1
